### ISSUE TITLE
Comment on use within a Quarto web page

### ISSUE THREAD

**Issue by cgoo4** [trelliscope/trelliscope#11]
Placing a Trelliscope inside a Quarto html web page ([see example](https://www.quantumjitter.com/project/wood/)), I found that adding `#| output: asis` to the code chunk avoids a scroll bar that merely scrolls to unwanted empty space.

With or without the `asis`, the figure does also butt up against a subsequent heading, so I inserted an empty level-3 heading (`###`).

```
#| label: trelliscope
#| out-width: "100%"
#| out-height: "500px"
#| scale: 0.5
#| output: asis
```

**Comment by hafen** [comment]
Thanks! I have added a note in the vignette that will show up with the next update.
