### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by olivroy** [trelliscope/trelliscope#12]
If you want to publish the package to CRAN, you may have to change the package name!

A package named trelliscope already existed on CRAN https://cran.r-project.org/package=trelliscope

Maybe trelliscope2?

Meanwhile, to make binaries available, you may consider publishing it to r universe?

Follow the steps https://r-universe.dev/ and click setup for this!

**Comment by hafen** [comment]
Good point. I was the author and maintainer of that package and was planning on submitting this as an update to that package. I'd love to avoid a rename.

Also yes good idea it would be great to publish to R Universe in the mean time.

**Comment by olivroy** [comment]
Oh I was not aware you were the author of the archived package! I beliebe all is good in that case then!
