### ISSUE TITLE
Trelliscope rendering in an R Markdown and Knitted HTML file

### ISSUE THREAD

**Issue by David-Degnan** [trelliscope/trelliscope#13]
Hello there! 

I followed the example here: [https://trelliscope.org/trelliscope/articles/embed.html](url) and I can't get the trelliscope to render within the R markdown document and subsequent HTML file. It instead renders in the viewer pane. Is there something I'm doing wrong? Can the documentation be updated with a complete example of an Rmd file? Thank you!

![Markdown_File](https://github.com/trelliscope/trelliscope/assets/40248272/b6a7e0a7-f032-4baf-bcd7-bdc70118dd2e)
![Rendered_HTML](https://github.com/trelliscope/trelliscope/assets/40248272/91b6b8f5-f178-480b-b862-3512b725fad7)
 
R Version: 4.3.0
Trelliscope Version: 0.1.9
MacOS Version: 14.2.1

**Comment by hafen** [comment]
Hi @David-Degnan - I think the only thing missing is setting `self_contained: false` in the output specification. This is mentioned in the docs but not prominently. Great idea to have a full example. I'll add that. Here's a minimal full example below. I have verified that it works but if it still doesn't work for you we can diagnose further.

````markdown
---
title: "Trelliscope RMarkdown Embedding"
output:
  html_document:
    self_contained: false
---

# Mars Rover Images

```{r mars_trelliscope, out.width="100%", out.height="700px", scale=0.5}
library(trelliscope)
d <- as_trelliscope_df(mars_rover, name = "mars rover")
view_trelliscope(d)
```
````

**Comment by David-Degnan** [comment]
Hey there! So sorry that I didn't get back to this sooner. I tried it, and it works when I run the display in chrome, but not locally in the R studio pop-up window. Luckily, I am happy enough with this. Thanks!

**Comment by hafen** [comment]
Great! I wonder if there is a way to bypass the RStudio pop-up as I would assume most users would stop there and assume it's broken?
